### ISSUE TITLE
Errors spec

### ISSUE THREAD

**Issue by divyenduz** [prisma/specs#113]
### Tasks

- [x] Unknown errors
- [x] User facing errors and engineer facing error logs
- [x] Masking sensitive data from error logs https://github.com/prisma/specs/issues/57
- [x] Software consumable errors (disable pretty printing as it makes reading serialized error difficult, maybe dev/prod mode) https://github.com/prisma/photonjs/issues/195 -- This will move to `Photon.js` spec
- [x] Error types/causes and surface area handling strategy
- [x] Known errors
- [x] How do different clients of SDK (Photon, CLI, Studio) handle different errors? (including bubbling)
- [x] Recovery path from known errors
- [x] User friendly errors (How and what errors bubble up? Error codes etc)
- [x] Do we need prefixes in SDK at all? Like `PVE0024` or `P0024`
- [x] Do we need code and/or prefixes in SDK users? 

### Meta

- [x] https://github.com/prisma/specs/issues/39

---

Pull Request: https://github.com/prisma/specs/pull/116

**Comment by mavilein** [comment]
I think this spec is now in a state where we can try to implement it :+1:

The only thing that we need to figure out is the exact shape of the returned error json. But i think this is an implementation detail right now as users do not interact with it directly.
Backend and @timsuchanek  will figure out a structure that is compatible with this spec.

**Comment by schickling** [comment]
More feedback continued over here: #204
