### ISSUE TITLE
Polish UI elements of `init` flow

### ISSUE THREAD

**Issue by nikolasburk** [prisma/specs#99]
The [current version](https://github.com/prisma/specs/tree/linearize-init/cli) of the `init` flow depicts the flows ([mostly](https://github.com/prisma/specs/issues/98)) accurately. However, the UI elements are partly inconsistent, most notably in terms of spacing and indentation.

- [ ] Ensure that indentation is consistent in all terminal screens across the different pages.
- [ ] Use proper punctuation (every sentence in title/subtitle of a screen should have proper punctuation, i.e. they should end with a period)
- [ ] Remove `Previous selections` dropdown from all pages
- [ ] Optimization: Currently `SUCCESS` and `ERROR` messages are always created manually using combinations of `Color` and `Text`. It would be nice to have a `Success` and `Error` component that could be used for these messages.
